name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Changez cela selon votre branche par défaut

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # ou la version de Node.js que vous utilisez

      - name: Install dependencies
        run: npm install --legacy-peer-deps


      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build  # le dossier de build de votre projet
